apiVersion: v1
kind: Service
metadata:
  name: cluster-manager
spec:
  selector:
    app: swiftcloud
    component: cluster-manager
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP